### ISSUE TITLE
Code for Squeeze

### ISSUE THREAD

**Issue by shaido987** [NetManAIOps/Squeeze#1]
Hello,

I have been doing some research on multi-dimensional root cause localization problems and tried out a couple of different methods. I think Squeeze takes an intuitive approach to solve the problem and I want to try it out on my dataset. Is there any plan to release the source code and upload it here to github?

Best regards,
Marcus

**Comment by lizeyan** [comment]
I am going through an internal process to release the code. I will update this issue when it is ready.

**Comment by lizeyan** [comment]
You are welcome to open a issue here if you have any question about Squeeze's implementation, and I am glad to help you.

**Comment by shaido987** [comment]
Thanks, I started implementing it myself already. I will contact you if I have any trouble.

**Comment by wangyuyue** [comment]
Hi, so is the code available now? @lizeyan

**Comment by RayDean** [comment]
I am also very interested in your source code, would you pls push the process....Thanks

**Comment by Capt-Rayn** [comment]
Excuse me, is the code now available?
I am very interested in your source code.
Looking forward to your reply.

**Comment by UTimeStrange** [comment]
Hello,
I came up with a simple method that can achieve similar F1-score(compared to your paper) on your dataset, without using GRE nor the squeeze(buttom up and top down) strategy. Looking forward to your code so that I can compete the time cost with your method.   >.<

**Comment by lizeyan** [comment]
> Hello,
> I came up with a simple method that can achieve similar F1-score(compared to your paper) on your dataset, without using GRE nor the squeeze(buttom up and top down) strategy. Looking forward to your code so that I can compete the time cost with your method. >.<

Our cooperating company is processing a patent application. After the patent is granted, the code will be permitted to be public.

**Comment by willxi** [comment]
hi Li，is the code can be public now?

**Comment by lizeyan** [comment]
> hi Li，is the code can be public now?

I am sorry, but we are still waiting for the result of the patent application. It seems extremely slow.

**Comment by scut2sjtu** [comment]
> > hi Li，is the code can be public now?
> 
> I am sorry, but we are still waiting for the result of the patent application. It seems extremely slow.

嗨，代码何时能公开呢？自己复现的效果达不到，有一些困惑

**Comment by lizeyan** [comment]
> > > hi Li，is the code can be public now?
> > 
> > 
> > I am sorry, but we are still waiting for the result of the patent application. It seems extremely slow.
> 
> 嗨，代码何时能公开呢？自己复现的效果达不到，有一些困惑

实在不好意思，合作方要求以前提交的相关专利通过之后才能公开代码😭。
你有什么问题可以参考一下一下别的issue里我和别人讨论的具体实现细节，或者有什么具体的问题你可以直接提新的issue

**Comment by mmjiang91** [comment]
嗨，请问代码可以公开了吗？

**Comment by lizeyan** [comment]
I am still pushing it. 
Questions about the implementation could be solved by reading the closed issues or opening new issues.

**Comment by tonyabracadabra** [comment]
Hi there, could u help me comparing the algorithm proposed in your paper vs the contribution of this paper? https://cs.stanford.edu/~deepakn/assets/papers/macrobase-sigmod17.pdf Are they fallen into the same category? Thanks a lot!

**Comment by leanceaner** [comment]
hi，现在代码可以公开了吗？自己复现效果总不尽人意：（

**Comment by lizeyan** [comment]
> hi，现在代码可以公开了吗？自己复现效果总不尽人意：（

我问一下

**Comment by lizeyan** [comment]
The implementation is released now

**Comment by shaido987** [comment]
Thank you for the update.

**Comment by scut2sjtu** [comment]
> 
感谢
