### ISSUE TITLE
关于cuboid中切分点，计算属性GPS值

### ISSUE THREAD

**Issue by mambasmile** [NetManAIOps/Squeeze#10]
你好，在论文中遍历cuboid的切分点时，描述的不是很清楚

![image](https://user-images.githubusercontent.com/19345320/171355234-3ba6837c-70aa-4f56-bc8c-3bffb73765e9.png)

查看了一下源代码（squeeze.py文件165行，代码如下），代码里提到是先排序，然后将某点之前所有的属性值都当作是异常的，剩下的当作正常的来求GPS值；从实际情况来看，是否应该是当前属性值为异常，剩下所有的属性值是正常的，以此来计算GPS值

![image](https://user-images.githubusercontent.com/19345320/171356228-231df78a-e009-4c45-b864-ec202efd5896.png)

**Comment by mambasmile** [comment]
![image](https://user-images.githubusercontent.com/19345320/172127986-a3144742-19d4-4060-a1a0-f7c039ccf182.png)

你好，squeeze.py文件中低236行，x[0]与原论文中的 n_ele，好像并不是等价的，这里是你们做的trick么；还是我理解错了

**Comment by lizeyan** [comment]
这里没有问题，`x[0]`的类型是`FrozenSet[AC]`，也就是一组属性组合。所以`len(x[0])`就是属性组合的个数，也就是`n_ele`
