### ISSUE TITLE
Specific implementation values and design choices

### ISSUE THREAD

**Issue by shaido987** [NetManAIOps/Squeeze#3]
Hi,

I have had some time lately to implement the Squeeze algorithm following the descriptions in the paper. I'm having some trouble replicating the final results using your open-sourced dataset. There are some specific design choices and parameter values that would help a lot in identifying the problem I'm having. If all or part of these could be provided it would be highly appreciated.

1) Filtering
I'm using the `KneeLocator` function from the [kneed](https://pypi.org/project/kneed/) python package as follows (I'm assuming this is what is used in the original code as well?):

```
kneedle = KneeLocator(x, y, S=1.0, curve='concave', direction='increasing')
```

What should the sensitivity value `S` be set to (1 is the default in the package)? 

2) Clustering (Algorithm 1)
    1) What is the number of bins used?
    2) Is the range of the bins static (always from `-2` to `2`) or dynamic depending on the input data?
    3) Should the values in the boundary bins be included in the cluster? In this case, can some values be in multiple clusters (for example if the histogram has values `0, 10, 5, 12, 0`, 5 will be in both the cluster with center `10` and center `12`)?

3) Sorting root causes (line 14 in Algorithm 2)
    1) Is the value of `C` global and fixed to the same value for all cuboids or is it different for each cuboid?
    2) Is `n_ele` (line 14) the sum of all `n_ele` (line 4) of the attribute combinations that are in the root cause (i.e., depending on the best partition)? Or is it the number of attribute combinations? For example, if the root cause found is ['c6', 'c7'], would `n_ele` be 2 or `sum([n_ele['c6'], n_ele['c7']])`? I found that if the sum of `n_ele`s is used then this term tends to dominate the sorting order, and the actual score is not too relevant.

Best regards,
Marcus

**Comment by lizeyan** [comment]
1. Yes, I use this package and I mention it in the paper. I use all the default parameters.
2. 
   i. the default setting in NumPy
   ii. According to the definition of deviation score, its range is [-1, 1].
   iii. No, a value is always in only one cluster.
3. 
  i. The formal definition of C is given in the paper. It is global for all cuboids.
  ii. n_ele in line 14 means the number of attribute combinations. It would be 2 in your example. Sorry that I misused the notion in the paper. The 'n_ele's in line 4 and line 14 denote different values.

**Comment by shaido987** [comment]
Thanks for the help. 

One follow-up question regarding the deviation score. In the paper, it is defined as `2*(f(e) - v(e)) / (f(e) + v(e))`. 
Shouldn't the range be [-2, 2] in this case? For example, if the predicted value is 1 while the real value is 0, then we have `2*1/1 = 2`.

**Comment by lizeyan** [comment]
> Thanks for the help.
> 
> One follow-up question regarding the deviation score. In the paper, it is defined as `2*(f(e) - v(e)) / (f(e) + v(e))`.
> Shouldn't the range be [-2, 2] in this case? For example, if the predicted value is 1 while the real value is 0, then we have `2*1/1 = 2`.

Yes, you are right. I forgot the constant 2.

**Comment by shaido987** [comment]
There is one more thing I'm having trouble with. When calculating the GPS score of a split, what elements should be considered? For example, if 'a4' has the highest decent score for cuboid A, then the first split will  `S_1=['a4']`, `S_2=['a1', 'a2', 'a3', 'a5', 'a6']`. 

- For the elements in `S_1`, should only the ones inside the cluster be considered? 
    - In this case, should `S_2` include any 'a4' not in `S_1` (i.e., all 'a4' outside the current cluster)?
- Or all 'a4' inside the total data?
    - In this case, should the 'total data' be after or before filtering with kneedle?

The problem I'm having here is that if I use all 'a4' in the total data, then the top root cause for both clusters will be 'a4', in this case missing the second root cause 'b25'. If I use only the elements inside the cluster then the final root cause for both clusters are `['a1', 'a2', 'a3', 'a4', 'a5', 'a6']`...

**Comment by lizeyan** [comment]
> There is one more thing I'm having trouble with. When calculating the GPS score of a split, what elements should be considered? For example, if 'a4' has the highest decent score for cuboid A, then the first split will `S_1=['a4']`, `S_2=['a1', 'a2', 'a3', 'a5', 'a6']`.
> 
> * For the elements in `S_1`, should only the ones inside the cluster be considered?
>   
>   * In this case, should `S_2` include any 'a4' not in `S_1` (i.e., all 'a4' outside the current cluster)?
> * Or all 'a4' inside the total data?
>   
>   * In this case, should the 'total data' be after or before filtering with kneedle?
> 
> The problem I'm having here is that if I use all 'a4' in the total data, then the top root cause for both clusters will be 'a4', in this case missing the second root cause 'b25'. If I use only the elements inside the cluster then the final root cause for both clusters are `['a1', 'a2', 'a3', 'a4', 'a5', 'a6']`...

For abnormal leaf attribute combinations (S1), I consider the attribute combinations only in the cluster; but for S2, I consider all the normal attribute combinations (i.e., attribute combinations in the current cluster and that cluster with deviation scores nearest to 0).

And note that kneedle filtering is only used for the clustering step. After that, in the in-cluster localization step, we do not filter any attribute combinations using kneedle.

**Comment by shaido987** [comment]
Despite all your help, I'm still not able to replicate the results. Using the open-sourced dataset, for root causes with a single element the results are comparable but when the number of root cause elements increases the result is a lot worse. 

I suspect the issue lies in the clustering part or maybe the evaluation. If you have time, could you take a look and see if there is something obvious that I have missed?

https://github.com/shaido987/multi-dim-baselines

(to run see the evaluate.py file)

**Comment by lizeyan** [comment]
> Despite all your help, I'm still not able to replicate the results. Using the open-sourced dataset, for root causes with a single element the results are comparable but when the number of root cause elements increases the result is a lot worse.
> 
> I suspect the issue lies in the clustering part or maybe the evaluation. If you have time, could you take a look and see if there is something obvious that I have missed?
> 
> https://github.com/shaido987/multi-dim-baselines
> 
> (to run see the evaluate.py file)

There are some advises:
1. I smooth the histogram before clustering using moving average, and I also smooth the CDF before finding knee points. For simplicity, I didn't mention it in the paper.
2. I use `np.histogram_bin_edges` to decide the histogram bins, rather than a fixed bins by `np.linspace`.
3. There are some tricks in finding relmax and relmin. For relative minimums, I use **less equal** as the comparator, and for relative maximums I use **greater**  as the comparator. It is different from `find_peak(-hist)`.
4. In knee points filtering, use `np.cumsum(vals)`. Both it and `np.cumsum(np.log(vals + 1))` works, but I found that in my code I used the former. Sorry that I forgot to update it in the paper.
