### ISSUE TITLE
Usage of the dataset D

### ISSUE THREAD

**Issue by YileiLI** [NetManAIOps/Squeeze#4]
Hello,

I noticed that there are two csv files (xxxxx.a & xxxxx.b) for each timestamp in the D dataset. Is one for the numerator and another for the denominator? Thanks.

King regards,

Yilei

**Comment by lizeyan** [comment]
> Hello,
> 
> 
> 
> I noticed that there are two csv files (xxxxx.a & xxxxx.b) for each timestamp in the D dataset. Is one for the numerator and another for the denominator? Thanks.
> 
> 
> 
> King regards,
> 
> 
> 
> Yilei
> 
> 
> 
> 
Yes, you're right. The .a file is the numerator and the .b file is the denominator

**Comment by YileiLI** [comment]
Thanks a lot!

**Comment by zmin1217** [comment]
Hello li,
How to use the file(injection_info.csv) to  compare the results of different algorithms，such as , squeeze and adtribution. And what does the meaning of each column in the injection_info.csv？ Thanks.
