### ISSUE TITLE
如何区分算法2中的 lin4  n_ele, lin5 n_descents, line14 n_ele？

### ISSUE THREAD

**Issue by kennethhome** [NetManAIOps/Squeeze#5]
您好，您的文章让我受益匪浅，感谢您发表的这边文章。下面是几个问题。
1，lin4  n_ele, lin5 n_descents, line14 n_ele 分别是什么？能否辛苦您用文章中的Table来具体表示？
2，文章中的descent score具体定义是什么？

感谢~

**Comment by lizeyan** [comment]
n_ele 指的是当前 cluster中 的 每个attribute combination 对应的 leaf attribute combinations 中，在当前cluster中的数量
n_descents 指的是当前 cluster中 的 每个attribute combination 对应的 leaf attribute combinations 的总数量
descent score就是n_descents 除以 n_ele
比如对于Table I 中的数据，假设我们当前的cluster是 {(Beijing, China Mobile), (Beijing, China Unicom)}
假设我们分析cuboid ISP
其中就有两个attribute combination: China Mobile和China Unicom
China Mobile的在当前cluster中的leaf attribute combination有一个（(Beijing, China Mobile)），总共有3个
China Unicom的在当前cluster中的leaf attribute combination有一个（(Beijing, China Unicom)），总共有6个
所以n_ele就是[1, 1]，n_descents就是[3, 6]，descen score就是[1/3, 1/6]

同样，在cuboid Province中，如果顺序是Beijing, Shanghai, Guangdong, Zhejiang, Shanxi, Jiangsu, Tianjin的话，显然n_ele就是[2, 0, 0, 0, 0, 0, 0]，n_descents就是[2, 1, 2, 1, 1, 1, 1]，descents score就是[1, 0, 0, 0, 0, 0, 0]。这样就能把Beijing排在最前面。
<img width="526" alt="image" src="https://user-images.githubusercontent.com/12494243/126447413-f6236838-d110-4fcb-bdd8-047d20d7ac8b.png">

**Comment by kennethhome** [comment]
感谢您的讲解，您的讲解很清楚，让我豁然开朗。

还有一个问题，想请教您一下。
您是如何想到使用GPS来衡量某个划分部分是否是根因；我该如何理解a(S)和f(S)在GPS公式中的作用；GPS的可解释性；

我有认真阅读您的论文，这些确实是我的疑问，虽然问的有点多，但还是希望您能帮忙解答，万分感谢~

**Comment by kennethhome** [comment]
非常感谢您的解答，您的解答让我豁然开朗，感谢~
