### ISSUE TITLE
sign of constant C

### ISSUE THREAD

**Issue by ZhangMingyang-cs** [NetManAIOps/Squeeze#6]
<img width="850" alt="20210820-162904@2x" src="https://user-images.githubusercontent.com/40710509/130204644-5c92175b-0b02-4513-a208-ba0771eec5b5.png">

请问按这里的负号是为了保持 C >= 0 吗？
在实验中遇到了 C < 0 的情况，导致 GPS 越大，最终的得分越低。
不知可否取 C 的绝对值？

**Comment by lizeyan** [comment]
不好意思，忘记回了。
这个是当时投稿版本的一个bug，这个公式计算出来的本意应该是保证非负的来着。
只是正好我们当时的数据大部分跑出来都是正的，所以当时我恰好没有发现而已。
这个是不能取绝对值的，需要修改公式。
你可以试试后来我们修改过的新的公式。
<img width="833" alt="Picsee-20210823143626" src="https://user-images.githubusercontent.com/12494243/130401634-20da653f-bb91-4dab-a463-12277839e9ae.png">

**Comment by ZhangMingyang-cs** [comment]
coverage of abnormal leaves 是 num_abnormal_leaves / num_leaves 吗？

**Comment by lizeyan** [comment]
是指 cluster 中的 abnormal leaves 占所有 leaves 的比例

**Comment by ZhangMingyang-cs** [comment]
感谢大佬

**Comment by shaido987** [comment]
For `num_attr` it is the actual number of attributes (e.g., 4 in most of the data) and not the total number of attribute values that is used for the original computation of C?

**Comment by lizeyan** [comment]
The notation `num_cluster` denotes the number of clusters,
`num_attr` denotes the number of all distinct attribute values, 
and `coverage of abnormal leaves` denotes the  ratio of the number of all leaf attribute combinations in all clusters to the number of all leaf attribute combinations.

> 不好意思，忘记回了。
> 这个是当时投稿版本的一个bug，这个公式计算出来的本意应该是保证非负的来着。
> 只是正好我们当时的数据大部分跑出来都是正的，所以当时我恰好没有发现而已。
> 这个是不能取绝对值的，需要修改公式。
> 你可以试试后来我们修改过的新的公式。
> <img alt="Picsee-20210823143626" width="833" src="https://user-images.githubusercontent.com/12494243/130401634-20da653f-bb91-4dab-a463-12277839e9ae.png">

**Comment by shaido987** [comment]
Thank you, I understand. So `g_attribute` above should use `sum([len(attrs) for attrs in self.attribute_values])` instead of `len(self.attribute_names)`.

**Comment by lizeyan** [comment]
> Thank you, I understand. So `g_attribute` above should use `sum([len(attrs) for attrs in self.attribute_values])` instead of `len(self.attribute_names)`. 
> 
> 
> 
> Adjusted code if it helps someone:
> 
> 
> 
> ```python
> 
> g_cluster = np.log(len(self.cluster_list) + 1) / len(self.cluster_list)
> 
> num_attr = sum([len(attrs) for attrs in self.attribute_values])
> 
> g_attribute = num_attr / np.log(num_attr + 1)
> 
> g_coverage = -np.log(sum([len(cluster) for cluster in self.cluster_list]) / len(self.data_list[0]))
> 
> ```

Yes
