### ISSUE TITLE
关于搜索空间的计算

### ISSUE THREAD

**Issue by mambasmile** [NetManAIOps/Squeeze#9]
作者您好，想问问搜索空间的计算方法

![image](https://user-images.githubusercontent.com/19345320/160518640-26f7f202-908a-406b-8e8a-b64c3c7ec6ba.png)
这里的搜索空间为啥是 2^(7+2+9)-1，是如何计算的？

![image](https://user-images.githubusercontent.com/19345320/160518730-23fa3d28-a1e1-4f91-a909-82a70adacc80.png)
这里的s搜索空间为啥是2^(4+2+5)-1，是如何计算的？

**Comment by lizeyan** [comment]
第一个表格：
属性为Province的属性组合有7个：Beijing, Shanghai, Guangdong, ...
属性为ISP的属性组合有2个：China Mobile, China Unicom.
属性为Province和ISP的属性组合有9个（等于表格的行数）：Beijing&China Mobile, Beijing&China Unicom, ....
所以现在一共有7+2+9个属性组合，我们的根因是在属性组合中取k个，k=1,2,3,.......,7+2+9
所以可能的根因数目就是C(7+2+9, 1) + C(7+2+9, 2) + .... + C(7+2+9, 7+2+9)=2^(7+2+9)-1,  其中C(n, k)表示组合数，代表从n个元素的集合中取k个有多少种不同的取法。

第二个表格同理

**Comment by mambasmile** [comment]
好的，谢谢

**Comment by mambasmile** [comment]
如果归因出来的结果是  （ Beijing， China Mobile，Beijing&China Mobile），这条归因其实是重复的，对么

**Comment by lizeyan** [comment]
对

**Comment by mambasmile** [comment]
![image](https://user-images.githubusercontent.com/19345320/175758401-4bcd2da4-1c0e-4d35-bafc-b9c46803d5c7.png)

您好，最后对因排序时，考虑GPS值和Succinctness，其中Succinctness考虑了因的异常样本的个数基于cubiod_layer，cubiod_layer比较好理解，遵循奥卡姆剃刀原则，而“异常样本的个数”是出于什么考虑呢
